# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import preprocessing_pb2 as preprocessing__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in preprocessing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PreProcessingServiceStub(object):
    """---------------------------------------------------------------------
    Serviço
    ---------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Normalize = channel.unary_unary(
                '/onehealth.preprocessing.PreProcessingService/Normalize',
                request_serializer=preprocessing__pb2.RawMeasurement.SerializeToString,
                response_deserializer=preprocessing__pb2.NormalizedMeasurement.FromString,
                _registered_method=True)
        self.NormalizeBatch = channel.unary_unary(
                '/onehealth.preprocessing.PreProcessingService/NormalizeBatch',
                request_serializer=preprocessing__pb2.BatchRequest.SerializeToString,
                response_deserializer=preprocessing__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/onehealth.preprocessing.PreProcessingService/Ping',
                request_serializer=preprocessing__pb2.PingRequest.SerializeToString,
                response_deserializer=preprocessing__pb2.PingResponse.FromString,
                _registered_method=True)


class PreProcessingServiceServicer(object):
    """---------------------------------------------------------------------
    Serviço
    ---------------------------------------------------------------------
    """

    def Normalize(self, request, context):
        """Normaliza uma única medição
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NormalizeBatch(self, request, context):
        """Normaliza um lote (mais eficiente para chamadas em rajada)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Healthcheck
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Normalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Normalize,
                    request_deserializer=preprocessing__pb2.RawMeasurement.FromString,
                    response_serializer=preprocessing__pb2.NormalizedMeasurement.SerializeToString,
            ),
            'NormalizeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.NormalizeBatch,
                    request_deserializer=preprocessing__pb2.BatchRequest.FromString,
                    response_serializer=preprocessing__pb2.BatchResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=preprocessing__pb2.PingRequest.FromString,
                    response_serializer=preprocessing__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onehealth.preprocessing.PreProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('onehealth.preprocessing.PreProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreProcessingService(object):
    """---------------------------------------------------------------------
    Serviço
    ---------------------------------------------------------------------
    """

    @staticmethod
    def Normalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.preprocessing.PreProcessingService/Normalize',
            preprocessing__pb2.RawMeasurement.SerializeToString,
            preprocessing__pb2.NormalizedMeasurement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NormalizeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.preprocessing.PreProcessingService/NormalizeBatch',
            preprocessing__pb2.BatchRequest.SerializeToString,
            preprocessing__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.preprocessing.PreProcessingService/Ping',
            preprocessing__pb2.PingRequest.SerializeToString,
            preprocessing__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
