# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analysis_pb2 as analysis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub(object):
    """---------------------------------------------------------------------
    Serviço
    ---------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeStatistics = channel.unary_unary(
                '/onehealth.analysis.AnalysisService/ComputeStatistics',
                request_serializer=analysis__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=analysis__pb2.StatisticsResponse.FromString,
                _registered_method=True)
        self.DetectPatterns = channel.unary_unary(
                '/onehealth.analysis.AnalysisService/DetectPatterns',
                request_serializer=analysis__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=analysis__pb2.PatternResponse.FromString,
                _registered_method=True)
        self.PredictHealthRisk = channel.unary_unary(
                '/onehealth.analysis.AnalysisService/PredictHealthRisk',
                request_serializer=analysis__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=analysis__pb2.HealthRiskResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/onehealth.analysis.AnalysisService/Ping',
                request_serializer=analysis__pb2.PingRequest.SerializeToString,
                response_deserializer=analysis__pb2.PingResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer(object):
    """---------------------------------------------------------------------
    Serviço
    ---------------------------------------------------------------------
    """

    def ComputeStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectPatterns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictHealthRisk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeStatistics,
                    request_deserializer=analysis__pb2.AnalysisRequest.FromString,
                    response_serializer=analysis__pb2.StatisticsResponse.SerializeToString,
            ),
            'DetectPatterns': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectPatterns,
                    request_deserializer=analysis__pb2.AnalysisRequest.FromString,
                    response_serializer=analysis__pb2.PatternResponse.SerializeToString,
            ),
            'PredictHealthRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictHealthRisk,
                    request_deserializer=analysis__pb2.AnalysisRequest.FromString,
                    response_serializer=analysis__pb2.HealthRiskResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=analysis__pb2.PingRequest.FromString,
                    response_serializer=analysis__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onehealth.analysis.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('onehealth.analysis.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """---------------------------------------------------------------------
    Serviço
    ---------------------------------------------------------------------
    """

    @staticmethod
    def ComputeStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.analysis.AnalysisService/ComputeStatistics',
            analysis__pb2.AnalysisRequest.SerializeToString,
            analysis__pb2.StatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectPatterns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.analysis.AnalysisService/DetectPatterns',
            analysis__pb2.AnalysisRequest.SerializeToString,
            analysis__pb2.PatternResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictHealthRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.analysis.AnalysisService/PredictHealthRisk',
            analysis__pb2.AnalysisRequest.SerializeToString,
            analysis__pb2.HealthRiskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onehealth.analysis.AnalysisService/Ping',
            analysis__pb2.PingRequest.SerializeToString,
            analysis__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
