# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preprocessing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'preprocessing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13preprocessing.proto\x12\x17onehealth.preprocessing\"\x8a\x01\n\x0eRawMeasurement\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04zona\x18\x02 \x01(\t\x12\x11\n\ttipo_dado\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\x12\x0f\n\x07\x66ormato\x18\x05 \x01(\t\x12\x0f\n\x07unidade\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\"\xa6\x01\n\x15NormalizedMeasurement\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04zona\x18\x02 \x01(\t\x12\x11\n\ttipo_dado\x18\x03 \x01(\t\x12\r\n\x05valor\x18\x04 \x01(\x01\x12\x12\n\nunidade_si\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x0e\n\x06valido\x18\x07 \x01(\x08\x12\x13\n\x0bobservacoes\x18\x08 \x01(\t\"I\n\x0c\x42\x61tchRequest\x12\x39\n\x08medicoes\x18\x01 \x03(\x0b\x32\'.onehealth.preprocessing.RawMeasurement\"Q\n\rBatchResponse\x12@\n\x08medicoes\x18\x01 \x03(\x0b\x32..onehealth.preprocessing.NormalizedMeasurement\"\x1d\n\x0bPingRequest\x12\x0e\n\x06origem\x18\x01 \x01(\t\"3\n\x0cPingResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\xb2\x02\n\x14PreProcessingService\x12\x64\n\tNormalize\x12\'.onehealth.preprocessing.RawMeasurement\x1a..onehealth.preprocessing.NormalizedMeasurement\x12_\n\x0eNormalizeBatch\x12%.onehealth.preprocessing.BatchRequest\x1a&.onehealth.preprocessing.BatchResponse\x12S\n\x04Ping\x12$.onehealth.preprocessing.PingRequest\x1a%.onehealth.preprocessing.PingResponseB\x1a\xaa\x02\x17OneHealth.PreProcessingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preprocessing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027OneHealth.PreProcessing'
  _globals['_RAWMEASUREMENT']._serialized_start=49
  _globals['_RAWMEASUREMENT']._serialized_end=187
  _globals['_NORMALIZEDMEASUREMENT']._serialized_start=190
  _globals['_NORMALIZEDMEASUREMENT']._serialized_end=356
  _globals['_BATCHREQUEST']._serialized_start=358
  _globals['_BATCHREQUEST']._serialized_end=431
  _globals['_BATCHRESPONSE']._serialized_start=433
  _globals['_BATCHRESPONSE']._serialized_end=514
  _globals['_PINGREQUEST']._serialized_start=516
  _globals['_PINGREQUEST']._serialized_end=545
  _globals['_PINGRESPONSE']._serialized_start=547
  _globals['_PINGRESPONSE']._serialized_end=598
  _globals['_PREPROCESSINGSERVICE']._serialized_start=601
  _globals['_PREPROCESSINGSERVICE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
